package com.orcl.sync.model.hibernate.hibernate;
// Generated 2017-4-27 9:47:22 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrUserDepartmentPosition generated by hbm2java
 */
@Entity
@Table(name = "HR_USER_DEPARTMENT_POSITION", schema = "SCOTT")
public class HrUserDepartmentPosition implements java.io.Serializable {

	private String id;
	private String sysUserId;
	private String departmentId;
	private String deptPositionId;
	private Integer masterflag;
	private String createBy;
	private String createName;
	private Date createDate;
	private String updateBy;
	private String updateName;
	private Date updateDate;

	public HrUserDepartmentPosition() {
	}

	public HrUserDepartmentPosition(String id) {
		this.id = id;
	}

	public HrUserDepartmentPosition(String id, String sysUserId, String departmentId, String deptPositionId,
			Integer masterflag, String createBy, String createName, Date createDate, String updateBy, String updateName,
			Date updateDate) {
		this.id = id;
		this.sysUserId = sysUserId;
		this.departmentId = departmentId;
		this.deptPositionId = deptPositionId;
		this.masterflag = masterflag;
		this.createBy = createBy;
		this.createName = createName;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateName = updateName;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "SYS_USER_ID", length = 36)
	public String getSysUserId() {
		return this.sysUserId;
	}

	public void setSysUserId(String sysUserId) {
		this.sysUserId = sysUserId;
	}

	@Column(name = "DEPARTMENT_ID", length = 36)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "DEPT_POSITION_ID", length = 36)
	public String getDeptPositionId() {
		return this.deptPositionId;
	}

	public void setDeptPositionId(String deptPositionId) {
		this.deptPositionId = deptPositionId;
	}

	@Column(name = "MASTERFLAG", precision = 6, scale = 0)
	public Integer getMasterflag() {
		return this.masterflag;
	}

	public void setMasterflag(Integer masterflag) {
		this.masterflag = masterflag;
	}

	@Column(name = "CREATE_BY", length = 36)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "CREATE_NAME", length = 32)
	public String getCreateName() {
		return this.createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 36)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "UPDATE_NAME", length = 32)
	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
